(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))h(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&h(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function h(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const b="/vanilla-app-template/assets/1-CLRonGvI.png",H="/vanilla-app-template/assets/2-DE6u2ZYd.png",I="/vanilla-app-template/assets/3-BK6TW9ee.png",_="/vanilla-app-template/assets/4-CavHCw7H.png",M="/vanilla-app-template/assets/5-DHCojVxa.png",T="/vanilla-app-template/assets/6-dW-SmJl3.png",x="/vanilla-app-template/assets/7-D8UGuM5J.png",o={img1:b,img2:H,img3:I,img4:_,img5:M,img6:T,img7:x},y=[{title:"Is the penis 8 inches or more in length?",avatar:o.img1},{title:"Have you exppirienced erectile problems or decrease in libido?",avatar:o.img2},{title:"Are you currently taking any medications or supplements that might affect your sexual health?",avatar:o.img3},{title:"Do you have any underlying health conditions, such as diabetes or hypertension?",avatar:o.img4},{title:"Have you ever undergone any previous treatments or surgeries for sexual enhancement or related issues?",avatar:o.img5},{title:"How important is it for you to have access to safe and effective medication for enhancing your sexual health?",avatar:o.img6},{title:"Do you think your wife is satisfied with the size of your penis?",avatar:o.img7}],d=document.getElementById("img_box"),p=document.getElementById("title_box"),B=document.getElementById("btn_yes"),w=document.getElementById("btn_no"),L=document.getElementById("backdrop"),l=document.getElementById("box_qst").children,m=document.getElementById("timer").children,v=document.getElementById("form_email"),A=document.getElementById("input_email");function q(n){return n.map(i=>`   <img
                src="${i.avatar}"
                alt="men"
                width="191"
                height="246"
              />`)}function C(n){return n.map(i=>`  <p class="text_quiz">
                    ${i.title}
                  </p>`)}const g=q(y),f=C(y);d.innerHTML=g[0];p.innerHTML=f[0];let s=0;console.log(s);l.length>0&&l[0].classList.add("active_quiz");function D(n){d.innerHTML=g[n],p.innerHTML=f[n]}function E(){s++,s>0&&l[s-1].classList.remove("active_quiz"),console.log(l.length),s<l.length&&l[s].classList.add("active_quiz"),s+1>l.length&&(L.classList.add("is_open"),O()),D(s)}B.addEventListener("click",E);w.addEventListener("click",E);let a=9,c=5;m[2].innerHTML=c;m[3].innerHTML=a;function O(n){setInterval(()=>{a--,a<0&&(c--,a=9),m[2].innerHTML=c,m[3].innerHTML=a,c===0&&a===0&&(c=6,a=0)},1e3)}v.addEventListener("submit",n=>{n.preventDefault();const r=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,i=A.value;if(i.trim().length===0){alert("Please fill in the email field");return}if(!r.test(i)){alert("Check if the email address is correct");return}d.innerHTML=g[0],p.innerHTML=f[0],L.classList.remove("is_open"),v.reset()});
//# sourceMappingURL=index.js.map
